### ISSUE TITLE
`ReplyData` should accomodate vectored I/O

### ISSUE THREAD

**Issue by asomers** [zargony/rust-fuse#120] opened 2018-12-04 01:04 UTC
It's possible that a filesystem's implementation services reads with vectored I/O.  This should lead to one data copy, when the data is copied from its vectored form in the reply buffer.  However `ReplyData` doesn't accomodate vectored I/O.  Its `data` method only accepts a single buffer, and it can only be called once.  This forces the filesystem to do a second data copy, just to pack the data into a single buffer.

Ideally `ReplyData` would accomodate vectored I/O either by accepting a vector of buffers, or by providing a method that can copy the data piecewise.

**Comment by zargony** [comment] 2019-06-22 13:52
Duplicate of #39. (thanks for raising awareness for vectored I/O. I'll make sure to take it into account with the redesign of reply types in rust-fuse 0.4)

**Closed by zargony** 2019-06-22 13:52 UTC
Labels: duplicate, enhancement
